# Jour 1 : Introduction à Pandas et Analyse Exploratoire des Données (EDA)

## Documentations
- [Pandas](https://pandas.pydata.org/pandas-docs/stable/)
- [Matplotlib](https://matplotlib.org/stable/users/index.html)


## 1. Bases de Pandas
> Préparez votre IDE pour une version de Python `>=3.11` et installez `pandas`,`pandas-stubs`, `openpyxl` et `matplotlib`.

In [2]:
!python --version

Python 3.14.0

In [3]:
!pip install pandas pandas-stubs openpyxl matplotlib

Requirement already satisfied: pandas in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: pandas-stubs in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (2.3.3.251219)
Requirement already satisfied: openpyxl in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (3.1.5)
Requirement already satisfied: matplotlib in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (3.10.8)
Requirement already satisfied: numpy>=1.26.0 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: types-pytz>=2022.1.1 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from pandas-stubs) (2025.2.0.20251108)
Requirement already satisfied: et-xmlfile in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: six>=1.5 in p:\prog\cc-2\cc 06 - data analysis - ind\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

> Configurez `pandas` afin que l'affichage par défaut des DataFrames affiche au
minimum 6 colonnes, au maximum 12 colonnes, au maximum 100 lignes de
contenu, au maximum 20 caractères par colonne et 240 caractères par ligne.

In [4]:
import pandas as pd

# Colonnes (min 6, max 12) avec 20 caractères max pour chaque
pd.set_option('display.max_columns', 12)    # 12 colonnes max
pd.set_option('display.max_colwidth', 20)   # 20 caractères par colonne

# Lignes (max 100 lignes) avec 240 caractères max par ligne
pd.set_option('display.max_rows', 100)      # 100 lignes max
pd.set_option('display.width', 240)         # 240 caractères par ligne


# Vérifier que les modifications ont bien été prises en compte
values = ['max_columns', 'max_colwidth', 'max_rows', 'width']
for value in values:
  print(f"{value}: {pd.get_option('display.' + value)}")

max_columns: 12
max_colwidth: 20
max_rows: 100
width: 240

Il n'existe pas d'option minimal pour les colonnes à afficher, cependant on peut contrôler l'affichage des colonnes via le DataFrame directement

`display.min_columns` n'existe pas

```df[[col1, col2, col3, col4, col5, col6 ]]``` -> on force l'affichage des colonnes sélectionnées, ici 6

> Créez un DataFrame depuis des valeurs aléatoires, avec 20 colonnes et 200
lignes, et vérifiez que son affichage respecte la configuration que vous avez
établie précédemment.

In [5]:
import random, string


# Pour vérifier que la taille maximale des colonnes est respectée, on va créer une fonction créant du texte avec au minimum 20 caractères
def random_text(min_len=20, max_len=30):
    return "".join(random.choice(string.ascii_letters + string.digits) for _ in range(random.randint(min_len, max_len))) 

# Création du DataFrame
df = pd.DataFrame(
    [[random_text() for _ in range(20)] for _ in range(200)],
    columns=[f"col_{i}" for i in range(20)],
)
df

,col_0,col_1,col_2,col_3,col_4,col_5,...,col_14,col_15,col_16,col_17,col_18,col_19
0,MvUrFQHaVIvGrqXo...,ha3zr1GHHKvMIZ5G...,57pEBAuoj9qGBFNB...,MHHVHDX4Hq11VJdc...,20gvr4AqVdGIneEj...,JKBIsldWxsuSYcIi...,...,c8i8gcefqy0w3Wgk...,nbs6TXzISZDKi9uR...,h08ow06qVfDASmei...,NiS2HWiqMMRAi9Wp...,jCLdzIlnt2oTp1jA...,W9yRgJOaVpFqoXmL...
1,2QgFxl9Zv0rDQHSi...,KBU4xnlr5eNliH68...,UG14KEEewBDBeQ1a...,UZfJrmK6nK0eNDTZ...,EtjNH5nT7l5aPzhq...,1XdQu59O8wF01pvf...,...,gAlGEzpqf1PkiETG...,BBPvtTjLgBLrR4cM...,flU1KmprzBvRtRGb...,m1e0qOnZQ752OTXq...,4Qo620GHAyEYtsau...,pimxoI32KmaIAsgE...
2,dkLfcj07yI9dvcQN...,jFQIgV4051xvM0Au...,To9db5H6M6rlzDVj...,eRXe9aXtNfaxwKOX...,g6gKIm5HS8QjM2Bo...,1pBHoWH4QhoNiHXp...,...,45bZKmclXK85K85E...,ZXNc6ymLezhVgAkC...,029NFuAAwcYVYFJB...,5ndLJk82wjMteUxN...,oR8tfR8By1TtoT5h...,lxwLNfXekubJENGD...
3,ElcnmlgOiZLC9Dwp...,qOQdh6hCQnfOWZj7...,qk6nDxh6Txp6z62W...,4wB65bdbmaJqLp1g...,5qCh4Ay3iN5a15nW...,rBQrL8kdA4JpdDjr...,...,wDd4e6wlP7E9bRPZ...,XS75nSPa15d9ZBYa...,3nsxJ8vmUNvR2BDK...,wZ93bOfGsFQXpkj1...,e0ORN43R9b3w80Sc...,sdE1T45gWnbLyG1H...
4,0dr8if6y3XHgWKss...,V887f3nEW3NbviK6...,JII32iYrs5h6gfVE...,tmn9SSiNYqgyyTgK...,avR01kNCFfAFHvXu...,kytfjQ8Sld29ajU3...,...,PZ8IFSKkyDkSYvKB...,cMXqdKIVGju1lhJT...,R7p8ZSwMl20jpsiT...,1NrZjvfdjOAGMdfH...,vTvSv97mz6jaTBMA...,DzaE9jWuss98jmTd...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,8gIhsLvl3C7FzY0Y...,NlXwFIPUWiNxpyrM...,mRS7XV2BzLIj5Vb8...,JR8edLg9c0mqcIp9...,9SrLE7yNwk6EUZTh...,2RGCvR0WywlndWQQ...,...,sxhM6ZAmqIPwkrpt...,3AtzMopfCMtJzt04...,4dhf06PKoWGox7mH...,gWsp0wqVJE0utkCh...,VZ1NMhw47VrFbtO8...,2JLkQwvfiyInABxC...
196,4JUmRrsjbow19sTv...,NxQOwwjdrZ8Inn4Q...,qtZdx6gJbvAq6P0K...,ENZ380T6CIDZg3lK...,dCr7lIbmLCr0Xli7...,qg2AOzjd04yT9CCZ...,...,hoPhgch30UZm80xF...,qlLTfmDQ6aAy1m0M...,ckGm1X7oHZLYarQ6...,pVp7ksGD84uK9PKx...,t2leXtsGHNXpi1rT...,BnokzaWG4EvtWxcy...
197,Fdoclw6DwKIn9Pnp...,ysNZsGV5hBrCfohu...,EoS7P9xfysOyiZx1...,GCI22E900ZekLIJF...,QFADFJuOrVjWmpQZ...,9pENkfsFduLDP17i...,...,Ss7jDxOgEcXxZnzS...,ERdXp1OlCoBi5gDA...,m3kgvf96vg1qLPKW...,fA38t2mAogZlPJtP...,5VzxwC8nNNr96XXL...,dT8K9BskEgvZtr2H...
198,N4EzhNgzchqPhdmK...,2UqrqsKdABgf38cH...,E0WjS2dguy0uH97i...,cBdqK5QwoFIp4XkA...,x6OTldtt5ZFsVB3q...,qr3TmC6fGff8Ivfz...,...,H8APOfcWnWgpSPjc...,ETscAyOVaQvZsQ3y...,DqhQWE05T7gCsAwg...,psnBfsQNCl0nQfV8...,sDj4QOzRhVyHpok7...,WStIl4KjCvTATsgG...
199,gLuwUUoWSoPxVTuB...,kJ0ztLvLp82xBBrj...,A180tYN3fa3Ed97P...,gCPCUIqwxCRZyShl...,yBuvkocFlBHrBCBK...,6USAhMQoMRMaLQOZ...,...,BplG5CZ6TV7YLcdX...,bFUEBd52SHcHWsL5...,caBKHfqpy13gS4xW...,HaTHBrGinZq1jRya...,Ewd0Hsp2I2rldTJ1...,Zy4uaAtCqGC8ycB2...

> Expliquez les concepts de base de Pandas, à savoir les `DataFrames` , les `Series` et les `Index`.

# Dataframes
Un `Dataframe`est un ensemble de `Series` Pandas indexées par une valeur.
C'est un tableau à 2 dimensions composés de lignes et de colonnes permettant de mettre en avant les relations entre les différentes variables du jeu de données.

Il peut contenir plusieurs type comme des nombres, du texte, des dates, etc par colonne comme une feuille Excel.

Chaque clé = nom de colonne

Chaque valeur = Series



# Series
Les `Series` sont des objets correspondants à des tableaux à une seule dimension.
C'est l'équivalent d'une seule colonne (ou ligne) avec un index.

Chaque colone de DataFrame est une Serie et associe à chaque valeur un index.


# Index
L'index est un objet contenant les étiquettes des axes (lignes et colonnes), permet d'identifier chaque ligne/colonnne et sert à aligner les données, faire des jointures etc

On peut voir l'index comme une série de données indentifiant des colonnes ou lignes

## 2. Chargement et exploration des données
> Chargez chaque feuille de calcul du fichier Excel dans des  DataFrame séparés,
> pour des variables nommées respectivement :
> - orders
> - territories
> - sales
> - resellers
> - dates
> - products
> - customers

In [6]:
# Création d'un dictionnaire global
dataframes = {}

# Stockage des noms de variables pour les différents dataframes
names = ['orders', 'territories', 'sales', 'resellers', 'dates', 'products', 'customers']

# Lecture du fichier Excel
sheets = pd.read_excel("datas/CC-AIBD-DataAnalyse-donnees.xlsx", sheet_name=None)

# Pour chaque feuille du fichier, on stocke le dataframe dans le dictionnaire global
for i, (_, df) in enumerate(sheets.items()):
    dataframes[names[i]] = df

# Exemple d'affichage d'un dataframe
dataframes['territories']

    SalesTerritoryKey          Region         Country          Group
0                   1       Northwest   United States  North America
1                   2       Northeast   United States  North America
2                   3         Central   United States  North America
3                   4       Southwest   United States  North America
4                   5       Southeast   United States  North America
5                   6          Canada          Canada  North America
6                   7          France          France         Europe
7                   8         Germany         Germany         Europe
8                   9       Australia       Australia        Pacific
9                  10  United Kingdom  United Kingdom         Europe
10                 11    Corporate HQ    Corporate HQ   Corporate HQ

> - Affichez les cinq premières lignes de chaque  DataFrame et vérifiez-en également les types de colonnes.
> - Affichez des informations de base sur les DataFrame via les méthodes info() et describe() pour obtenir des informations sur la taille, les types de données et les valeurs manquantes dans chaque DataFrame .
> - Si besoin, notez les colonnes qui ont un type qui semble incorrect vis-à-vis de leur usage
---
-> Cf présentation pour voir l'analyse des différents dataframes dans la présentation

> - Affichez des informations de distribution (dispersion) du coût standard des produits du catalogue. Affichez la médiane, l'écart-type et la variance.

Pour faire ça, nous allons utiliser `agg` qui va nous permettre d'appliquer une ou plusieurs fonctions d'aggrégation sur notre DataFrame ou sur un groupby afin de produire un tableau de statistiques

In [7]:
df = dataframes["products"]

stats = df["Standard Cost"].agg(["median", "std", "var"])
stats.index = ["Médiane", "Écart type", "Variance"]

stats

Médiane          204.625100
Écart type       497.076884
Variance      247085.428708
Name: Standard Cost, dtype: float64

> Calculez les mêmes informations, mais cette fois-ci par catégorie de produit (Category)

In [8]:
df = dataframes["products"]

stats = df.groupby("Category")["Standard Cost"].agg(["median", "std", "var"])
stats.columns = ["Médiane", "Écart type", "Variance"]

stats

              Médiane  Écart type       Variance
Category
Accessories   11.2163   13.127986     172.344014
Bikes        713.0798  552.407211  305153.726769
Clothing      26.1763   12.424381     154.365235
Components   187.1571  280.636563   78756.880441

## 3. Nettoyage des données
> Assurez-vous dans tous les `DataFrames` qu'il n'existe aucune cellule laissée vide. Si ce n'est pas le cas, affichez les identifiants des colonnes contenant des valeurs vides. Remplacez également ces valeurs par une valeur de repli si besoin

In [9]:
# Trouver les dataframes dans lesquels au moins une cellule a une valeur manquante
dataframes_with_empty_cell = []
for key, df in dataframes.items():
    if df.isna().any().any() > 0:
        dataframes_with_empty_cell.append(key)

print(dataframes_with_empty_cell)

['sales', 'products']

In [10]:
for df in dataframes_with_empty_cell:
    # On regarde les colonnes avec des valeurs manquantes pour les df trouvés
    print(dataframes[df].isna().sum())

SalesOrderLineKey             0
ResellerKey                   0
CustomerKey                   0
ProductKey                    0
OrderDateKey                  0
DueDateKey                    0
ShipDateKey                2113
SalesTerritoryKey             0
Order Quantity                0
Unit Price                    0
Extended Amount               0
Unit Price Discount Pct       0
Product Standard Cost         0
Total Product Cost            0
Sales Amount                  0
dtype: int64
ProductKey        0
SKU               0
Product           0
Standard Cost     0
Color            56
List Price        0
Model             0
Subcategory       0
Category          0
dtype: int64

Nous trouvons ici 2 colonnes problématiques : 
- `ShipDateKey` dans le dataframe `sales`
- `Color` dans le dataframe `products`

## 3.1.1 - `ShipDateKey` dans le dataframe `sales`

Par rapport à ShipDateKey, on remarque que dans le DataFrame, il y a 3 colonnes pour les dates :
- OrderDate en int64
- DueDateKey en int64
- ShipDateKey en float64 -> Ici le type de la colonne est en float sûrement à cause des valeurs manquantes

Je choisis ici de convertir les données en Int64 pour la colonne ShipDateKey afin de garder le concept de clé en int et en rendant nulle (\<NA\>) les valeurs manquantes que je mettrais à -1 pour les ShipDateKey non définies.

Je convertis en Int64 et pas en int64 car ici la colonne peut avoir des valeurs nulles. Si je garde en int64, vu qu'il y a des valeurs manquantes, la colonne va être convertie en float64.

In [11]:
dataframes['sales'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121253 entries, 0 to 121252
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   SalesOrderLineKey        121253 non-null  int64
 1   ResellerKey              121253 non-null  int64
 2   CustomerKey              121253 non-null  int64
 3   ProductKey               121253 non-null  int64
 4   OrderDateKey             121253 non-null  int64
 5   DueDateKey               121253 non-null  int64
 6   ShipDateKey              119140 non-null  float64
 7   SalesTerritoryKey        121253 non-null  int64
 8   Order Quantity           121253 non-null  int64
 9   Unit Price               121253 non-null  float64
 10  Extended Amount          121253 non-null  float64
 11  Unit Price Discount Pct  121253 non-null  int64
 12  Product Standard Cost    121253 non-null  float64
 13  Total Product Cost       121253 non-null  float64
 14  Sales Amount             121253 non-null  float64
dtypes: float64(6), int64(9)
memory usage: 13.9 MB

In [12]:
dataframes['sales']['ShipDateKey'] = dataframes['sales']['ShipDateKey'].astype("Int64")
dataframes['sales']['ShipDateKey'] = dataframes['sales']['ShipDateKey'].fillna(-1)

## 3.1.2 - `Color` dans le dataframe `products`

Ici, les valeurs nulles sont les couleurs des produits.

Je décide juste de remplacer NA par "Default" pour les couleurs nulles dans mon DataFrame.

In [13]:
dataframes['products'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ProductKey     397 non-null    int64
 1   SKU            397 non-null    object
 2   Product        397 non-null    object
 3   Standard Cost  397 non-null    float64
 4   Color          341 non-null    object
 5   List Price     397 non-null    float64
 6   Model          397 non-null    object
 7   Subcategory    397 non-null    object
 8   Category       397 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 28.0+ KB

In [14]:
dataframes['products']['Color'].fillna("Default", inplace=True)

In [15]:
dataframes['products'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ProductKey     397 non-null    int64
 1   SKU            397 non-null    object
 2   Product        397 non-null    object
 3   Standard Cost  397 non-null    float64
 4   Color          397 non-null    object
 5   List Price     397 non-null    float64
 6   Model          397 non-null    object
 7   Subcategory    397 non-null    object
 8   Category       397 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 28.0+ KB

In [16]:
# Vérification de la présence de valeurs nulles
for df in dataframes_with_empty_cell:
    # On regarde les colonnes avec des valeurs manquantes pour les df trouvés
    print(dataframes[df].isna().sum())

SalesOrderLineKey          0
ResellerKey                0
CustomerKey                0
ProductKey                 0
OrderDateKey               0
DueDateKey                 0
ShipDateKey                0
SalesTerritoryKey          0
Order Quantity             0
Unit Price                 0
Extended Amount            0
Unit Price Discount Pct    0
Product Standard Cost      0
Total Product Cost         0
Sales Amount               0
dtype: int64
ProductKey       0
SKU              0
Product          0
Standard Cost    0
Color            0
List Price       0
Model            0
Subcategory      0
Category         0
dtype: int64

> Vérifiez dans les ventes que le total des ventes est correct, notamment lorsque la valeur de remise (discount) est non nulle.

On nous demande ici de vérifier dans les ventes que le total des ventes est correct surtout si la valeur de remise est non null.
Je décide

In [19]:
df_sales = dataframes['sales']
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121253 entries, 0 to 121252
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   SalesOrderLineKey        121253 non-null  int64
 1   ResellerKey              121253 non-null  int64
 2   CustomerKey              121253 non-null  int64
 3   ProductKey               121253 non-null  int64
 4   OrderDateKey             121253 non-null  int64
 5   DueDateKey               121253 non-null  int64
 6   ShipDateKey              121253 non-null  Int64
 7   SalesTerritoryKey        121253 non-null  int64
 8   Order Quantity           121253 non-null  int64
 9   Unit Price               121253 non-null  float64
 10  Extended Amount          121253 non-null  float64
 11  Unit Price Discount Pct  121253 non-null  int64
 12  Product Standard Cost    121253 non-null  float64
 13  Total Product Cost       121253 non-null  float64
 14  Sales Amount             121253 non-null  float64
dtypes: Int64(1), float64(5), int64(9)
memory usage: 14.0 MB

In [33]:
# On vérifie que la colonne n'a pas de remise nulle
df_discount_not_null = df_sales["Unit Price Discount Pct"].isna()

# On vérifie que toutes les lignes ont une remise définie
df_discount_not_null.sum()

# 0 -> Aucune valeur nulle trouvée dans cette colonne

np.int64(0)

In [40]:
# On fait une copie sur le DataFrame actuel pour faire les calculs souhaités sans modifier le DataFrame de base
df_sales_copy = df_sales.copy()

# On recalcule les valeurs des ventes avec la remise prise en compte
df_sales_copy["Calculated_Sales_Amount"] = (df_sales_copy["Unit Price"] * df_sales_copy["Order Quantity"]) * ((100 - df_sales_copy["Unit Price Discount Pct"]) / 100)

test = (df_sales_copy["Sales Amount"] - df_sales_copy["Calculated_Sales_Amount"]).abs() > 0.01

df_errors = df_sales_copy[test]
df_errors

       SalesOrderLineKey  ResellerKey  CustomerKey  ProductKey  OrderDateKey  DueDateKey  ...  Extended Amount  Unit Price Discount Pct  Product Standard Cost  Total Product Cost  Sales Amount  Calculated_Sales_Amount
656             43875010          278           -1         346      20170813    20170823  ...       23663.9304                    0                1912.1544            22945.8528    23190.6518           23663.9304
658             43875012          278           -1         348      20170813    20170823  ...       25447.4246                    0                1898.0944            24675.2272    24938.4761           25447.4246
713             43879026          569           -1         223      20170816    20170826  ...          65.1768                    0                   5.7052               74.1676       63.8733              65.1768
734             43881008          346           -1         218      20170816    20170826  ...         109.7250                    0                   3.3963               71.3223      104.2388             109.7250
769             43884017          623           -1         345      20170817    20170827  ...       27607.9188                    0                1912.1544            26770.1616    27055.7604           27607.9188
...                  ...          ...          ...         ...           ...         ...  ...              ...                  ...                      ...                   ...           ...                  ...
60808           71949039           54           -1         484      20200615    20200625  ...          55.3320                    0                   2.9733               35.6796       54.2254              55.3320
60821           71952008          490           -1         594      20200615    20200625  ...         225.9960                    0                 308.2179              616.4358      135.5976             225.9960
60822           71952009          490           -1         595      20200615    20200625  ...         225.9960                    0                 308.2179              616.4358      135.5976             225.9960
60835           71952022          490           -1         476      20200615    20200625  ...         577.4175                    0                  26.1763              392.6445      548.5466             577.4175
60854           71952041          490           -1         592      20200615    20200625  ...         338.9940                    0                 308.2179              924.6537      203.3964             338.9940

[3282 rows x 16 columns]